use_frameworks!

platform :ios, '14.0'

target 'Home_Example' do
  pod 'Home', :path => '../', :testspecs => ['IntegratedTest', 'UnitTests']
  pod 'CoreEntities', :path => '../../CoreEntities'
 

  target 'Home_Tests' do
    inherit! :search_paths

    
  end
end
